collections:
  articles:
    output: true
  authors:
    output: true
  staff:
    output: true

excerpt_separator: <!--more-->

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
