title: A Classic Blog
domain: username.github.io
url: https://username.github.io

collections:
  articles:
    output: true
  lists:
    output: true
  authors:
    output: true
  staff:
    order:
      - lefay.md
      - moriarty.md
      - dewinter.md
      - defarge.md
      - hyde.md
    output: true

# Misc. settings
excerpt_separator: <!--more-->
google_analytics: 'UA—XXXXXXXX-X' # Add 'JEKYLL_ENV=production' prior to build
#     command if deploying on platform other than GitHub
#     e.g., JEKYLL_ENV=production bundle exec jekyll build
include:
  - _*.html
permalink: /:categories/:title/ # Remove in order for Paginate to work
sass:
  style: compressed

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# GitHub
repository: username/repo-name
github: [metadata]
