title: A Classic Blog
domain: jsherling.github.io
url: https://jsherling.github.io
baseurl: /classic-blog

twitter:
  username: bubblejuice
  card: summary
facebook:
  app_id: 1435
  publisher: 1435
  admins: 1435
social:
  name: Bubba Juice
  links:
    - https://twitter.com/BubbleJuice
    - https://www.facebook.com/bubba.juice
    - https://www.linkedin.com/in/BubbleJuice
    - https://github.com/BobJameson

collections:
  articles:
    output: true
  lists:
    output: true
  authors:
    output: true
  staff:
    order:
      - lefay.md
      - moriarty.md
      - dewinter.md
      - defarge.md
      - hyde.md
    output: true

permalink: /:categories/:title/

excerpt_separator: <!--more-->

include:
  - _*.html

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

repository: jsherling/classic-blog
github: [metadata]

