title: Your awesome title
email: no_reply@zixzoo.com
description: >- # this means to ignore newlines until "baseurl:"
  My father's family name being Pirrip, and my Christian name Philip, my infant
  tongue could make of both names nothing longer or more explicit than Pip. So,
  I called myself Pip, and came to be called Pip.
baseurl: '' # the sub path of your site, e.g. /blog
url: 'www.zixzoo.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ''
github_username:  jsherling

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
